apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: prod-mysql
    tier: db
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: mysql
    nodePort: 31320
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prod-mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.25
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql"
        - name: MYSQL_DATABASE
          value: "mysql"
        - name: MYSQL_USER
          value: "mysql"
        - name: MYSQL_PASSWORD
          value: "mysql"